[project]
name = "incident-agent-workflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiohttp>=3.14.1",
    "azure-identity>=1.25.3",
    "azure-storage-blob>=12.30.0",
    "azure-storage-queue>=12.17.0",
    "fastapi>=0.138.0",
    "fastapi-cli>=0.0.27",
    "httpx>=0.28.1",
    "pydantic>=2.13.4",
    "pydantic-ai>=2.1.0",
    "python-dotenv>=1.2.2",
]

[tool.fastapi]
entrypoint = "app.main:app"

