import datetime
import json
import os
from pathlib import Path
from typing import Any

from dotenv import load_dotenv
from fastapi import HTTPException
from pydantic import BaseModel, field_validator
from azure.core.exceptions import ResourceExistsError, ResourceNotFoundError
from azure.storage.blob.aio import BlobServiceClient

load_dotenv()


class Patch(BaseModel):
    """Patch changes generated by the agent."""
    data: dict[str, Any]
class Tools:
    artifact_container = "artifacts"
    config_container = "infrastructure-settings"
    patch_container = "patches"

    def __init__(self):
        connection_string = os.getenv("AZURE_STORAGE_CONNECTION_STRING", "")
        if not connection_string:
            raise HTTPException(status_code=500, detail="AZURE_STORAGE_CONNECTION_STRING is not configured")
        self.project_root = Path(__file__).resolve().parents[2]
        self.mock_patches_dir = self.project_root / "mock_patches"
        self.blob_service_client = BlobServiceClient.from_connection_string(connection_string)

    async def initialize(self) -> None:
        """Create required containers once during application startup."""
        for container_name in (
            self.artifact_container,
            self.config_container,
            self.patch_container,
        ):
            container_client = self.blob_service_client.get_container_client(container_name)
            try:
                await container_client.create_container()
            except ResourceExistsError:
                pass

    async def close(self) -> None:
        await self.blob_service_client.close()

    async def get_blob_client(self, container_name: str, blob_name: str):
        container_client = self.blob_service_client.get_container_client(container_name)
        return container_client.get_blob_client(blob_name)

    async def fetch_artifact(self, artifact_path: str):
        if not artifact_path:
            raise HTTPException(status_code=400, detail="Artifact path is required")

        blob_client = await self.get_blob_client(self.artifact_container, artifact_path)
        try:
            return await blob_client.download_blob()

        except ResourceNotFoundError:
            raise HTTPException(status_code=404, 
                                detail=f"Blob artifact not found: {artifact_path}")

    async def fetch_infrastructure_settings(self, system_config_path: str):
        if not system_config_path:
            raise HTTPException(status_code=400, detail="System configuration path is required")

        blob_client = await self.get_blob_client(self.config_container, system_config_path)
        try:
            stream = await blob_client.download_blob()
            content = await stream.readall()
            return json.loads(content)
        except ResourceNotFoundError:
            raise HTTPException(status_code=404, detail=f"Configuration blob not found: {system_config_path}")


    async def post_patch(self, incident_id: str, patch: Patch) -> str:
        try:
            created_date = datetime.datetime.now().strftime("%d-%m-%Y_%H-%M-%S")
            safe_incident_id = incident_id.replace("/", "_").replace("\\", "_")
            file_name = f"patch_{safe_incident_id}_{created_date}.json"
            file_path = self.mock_patches_dir / file_name
            self.mock_patches_dir.mkdir(parents=True, exist_ok=True)

            with file_path.open("w", encoding="utf-8") as file:
                json.dump(patch.data, file, indent=4)

            blob_client = await self.get_blob_client(self.patch_container, file_name)
            json_bytes = json.dumps(patch.data).encode("utf-8")
            await blob_client.upload_blob(json_bytes, overwrite=True)

            return f"{self.patch_container}/{file_name}"
        except Exception as e:
            raise HTTPException(status_code=500, detail="Failed to store patch") from e

